from __future__ import annotations

import json
import os
import psycopg

from ai_operator.memory.db import get_db_url


def main() -> None:
    db_url = get_db_url()

    # A tiny sample unified diff patch (does not have to apply yet)
    patch = """diff --git a/README.md b/README.md
index 0000000..1111111 100644
--- a/README.md
+++ b/README.md
@@ -0,0 +1,5 @@
+# AI Operator
+
+Artifact demo patch written by worker.
+This file may or may not exist yet—this is just demonstrating patch artifact output.
+"""

    md = """# AI Operator — Artifact Demo

This markdown file was generated by `doc.build`.

## What happened
- Worker claimed a task
- Produced an artifact file under `artifacts/docs/`
- Recorded the event trail in `memory`
"""

    tasks = [
        {
            "type": "repo.change",
            "payload": {
                "name": "demo_patch",
                "patch": patch,
                "meta": {"purpose": "portfolio_demo"},
            },
            "priority": 10,
            "max_attempts": 3,
        },
        {
            "type": "doc.build",
            "payload": {
                "name": "demo_doc",
                "markdown": md,
                "meta": {"purpose": "portfolio_demo"},
            },
            "priority": 10,
            "max_attempts": 3,
        },
    ]

    sql = """
    INSERT INTO tasks (type, payload, priority, max_attempts)
    VALUES (%(type)s, %(payload)s::jsonb, %(priority)s, %(max_attempts)s)
    RETURNING id;
    """

    with psycopg.connect(db_url) as conn:
        with conn.cursor() as cur:
            for t in tasks:
                cur.execute(
                    sql,
                    {
                        "type": t["type"],
                        "payload": json.dumps(t["payload"]),
                        "priority": t["priority"],
                        "max_attempts": t["max_attempts"],
                    },
                )
                tid = cur.fetchone()[0]
                print("ENQUEUED", t["type"], tid)
        conn.commit()


if __name__ == "__main__":
    main()